FROM nginx:1.21.0

WORKDIR /usr/share/nginx/html
ADD ./template.html /usr/share/nginx/html/template.html
ENV JENKINS_BUILD_NO=0

RUN sed 's/{{build_num}}/${JENKINS_BUILD_NO}/g' template.html > index.html